// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Menu struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type NewMenu struct {
	Text string `json:"text"`
}
